### ISSUE TITLE
TypeError: connect() argument 3 must be string, not int

### ISSUE THREAD

**Issue by d-bo** [philipsoutham/py-mysql2pgsql#89] opened 2015-08-11 13:10 UTC
Hello ! Get error from the topic.

Using this conf:

``` python
# if a socket is specified we will use that
# if tcp is chosen you can use compression
mysql:
 hostname: 127.0.0.1
 port: 3306
 socket: /tmp/mysql.sock
 username: root
 password: 12345
 database: podcast
 compress: false
destination:
 # if file is given, output goes to file, else postgres
 file: 
 postgres:
  hostname: 127.0.0.1
  port: 5432
  username: postgres
  password: 12345
  database: podcast

# if tables is given, only the listed tables will be converted.  leave empty to convert all tables.
#only_tables:
#- table1
#- table2
# if exclude_tables is given, exclude the listed tables from the conversion.
#exclude_tables:
#- table3
#- table4

# if supress_data is true, only the schema definition will be exported/migrated, and not the data
supress_data: false

# if supress_ddl is true, only the data will be exported/imported, and not the schema
supress_ddl: false

# if force_truncate is true, forces a table truncate before table loading
force_truncate: false
```

**Comment by iceberk** [comment] 2016-01-12 18:29
the problem is that your password is number. just escape it with qoutes:
password: '12345'

**Comment by kworr** [comment] 2017-09-23 21:03
This is already fixed in current version. Thank you!

**Closed by kworr** 2017-09-23 21:03 UTC

**Comment by Hemal-Mamtora** [comment] 2020-01-02 12:54
Got this error while using Django with python3.
The solution of @iceberk worked for me. Thanks
